- name: Updates apt cache
  apt: update_cache=true

- name: Installs necessary packages
  apt: pkg={{ item }} state=latest
  with_items:
    - python-pip
    - build-essential
    - python-dev
    - git
    - vim
    - rabbitmq-server
    - redis-server

- name: Install Python packages
  pip: name={{ item }}
  with_items:
    - celery
    - redis

- name: Push celeryd init script
  copy: src=celeryd dest=/etc/init.d/ mode=0777 owner=root group=root

- name: Push celerybeat init script
  copy: src=celerybeat dest=/etc/init.d/ mode=0777

- name: Pushes celeryd configuration
  template: src=celeryd.j2 dest=/etc/default/celeryd mode=0640 owner=root group=root

- name: Create celery group
  group: name=celery state=present

- name: Create celery user
  user: name=celery group=celery

- name: Update user vagrant groups
  user: name=vagrant groups=celery append=yes

- name: update directory
  file: path=/data/code state=directory owner=vagrant group=celery
